---
- name: Instalar PHP-8.1
  hosts: ubuntu
  become: yes
  
  tasks:
    - name: Adicionar repositório PPA para PHP 8.1
        apt_repository:
        repo: ppa:ondrej/php
        state: present

    - name: Atualizar o cache do APT
      apt:
        update_cache: yes

    - name: Instalar PHP 8.1 e extensoes
      apt:
        name:
          - php8.1-fpm
          - php8.1-mysql
          - php8.1-xml
          - php8.1-json
          - php8.1-mbstring
          - php8.1-gd
          - php8.1-curl
          - php8.1-zip
        state: present
        
    - name: Copiar o arquivo de configuracao do PHP
      copy:
        src: 'files/www.conf'
        dest: '/etc/php/8.1/fpm/pool.d/www.conf'
        owner: root
        group: root
        mode: '0644'

    - name: Iniciar e habilitar o PHP-FPM
      service:
        name: php8.1-fpm
        state: started
        enabled: yes

# handlers:
#   - name: Reiniciar Nginx
#     service:
#       name: nginx
#       state: restarted
